### PR TITLE
(IMAGES-1323) Adds RedHat 9 support

### PR DESCRIPTION
**Pull request by mhashizume**
A companion PR to https://github.com/voxpupuli/beaker/pull/1719

### CODE REVIEW

**Review by GabrielNagy — APPROVED** [review]
This looks good :+1:, I also confirmed the fixtures are correct, not sure why the codecov check is failing.

**Comment by ekohl** [comment]
I'd really be in favor of dropping codecov. It's obviously not doing anything useful and only generates noise. That's my general impression of codecov, but especially true here.

**Comment by joshcooper** [comment]
Could we get a `beaker-hostgenerator` gem release that contains this fix? It looks like this is handled through the github action, but I wanted to ask before kicking it.

**Comment by GabrielNagy** [comment]
@joshcooper I can take care of this today; the steps for releasing are documented [here](https://github.com/voxpupuli/beaker-hostgenerator#make-a-new-release).

**Pull request merged**
