### PR TITLE
Modify osx11.2 to osx11

### PR DESCRIPTION
**Pull request by BobosilaVictor**
Related to : https://github.com/puppetlabs/puppet-agent/pull/2081

### CODE REVIEW

**Review by GabrielNagy — APPROVED** [review]
For Big Sur we're making the assumption (for now) that all Y releases of macOS 11 will still refer to Big Sur (as has been the case with 11.1, 11.2, and 11.3 beta). This is to avoid having to add a new platform for each minor release of Big Sur.

The vmpooler template should remain the same, as it reflects the underlying version of the machine we're building on, but the platform should be agnostic.

**Review by ekohl — COMMENTED** [review]
I'm not familiar with OS X but does it make sense to keep the old definition?

**Comment by GabrielNagy** [comment]
I don't think so, right now keeping 11.2 would be like having separate definitions for RedHat minor releases (like 8.1, 8.2, 8.3).

However... this is definitely something that might change at any point, especially since Apple doesn't communicate versioning details to external users. We can circle back if/when something changes.

**Comment by ekohl** [comment]
If supported minors aren't a thing for OS X I don't mind removing it. However, it is odd that for OS X 10 there are multiple minor versions. Is that a new policy for 11?

**Comment by GabrielNagy** [comment]
Ah, yes, they've decided to bump the major version for the first time in ~20 years 😄 

- https://en.wikipedia.org/wiki/MacOS_version_history#Version_11:_%22Big_Sur%22
- https://www.macworld.com/article/342024/after-20-years-of-os-x-macos-11-might-be-gone-after-big-sur.html

**Review by ekohl — APPROVED** [review]

**Comment by ciprianbadescu** [comment]
@ekohl, do you know when could we get a release with MacOS 11 support?
Thanks

**Comment by bastelfreak** [comment]
I raised https://github.com/voxpupuli/beaker-hostgenerator/pull/207 for a release

**Comment by ciprianbadescu** [comment]
@bastelfreak, much obliged

**Pull request merged**
